version: 2.1
# Use a package of configuration called an orb.
jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
          #  aws cloudformation deploy --template-file  --stack-name  --region us-east-1
            aws cloudformation create-stack --stack-name myStack --template-body file://template.yml  --region=us-east-1
            
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
