version: 2.1
# Use a package of configuration called an orb.
jobs:
  myjob1:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
     # - myjob1
      - create_infrastructure
